GET http://localhost:5000
###
GET http://localhost:5000/foods
###
POST http://localhost:5000/foods
Content-Type: application/json

{
  "name": "Oatmeal",
  "calories": 150,
  "protein": 5,
  "carbs": 27,
  "fat": 3
}
###
POST http://localhost:5000/food-entries
Content-Type: application/json

{
  "foodId": 1,
  "servings": 2,
  "entryDate": "2026-06-24"
}
###
GET http://localhost:5000/food-entries/2
###
GET http://localhost:5000/dashboard/today
###
DELETE http://localhost:5000/food-entries/2
